In [6]:
import math

import numpy as np
np.set_printoptions(suppress=True)


In [7]:
def cts(q):
    x = q[0]
    y = q[1]
    z = q[2]
    rho = np.sqrt(x**2+y**2+z**2)
    theta = float(math.degrees(np.arccos(z/rho)))
    phi = np.sign(y)*float(math.degrees(np.arccos(x/np.sqrt(x**2+y**2))))
    q_s = np.array([rho,theta,phi])
    return q_s
def stc(q):
    rho = (q[0])
    theta = math.radians(q[1])
    phi= math.radians(q[2])
    x = rho*np.sin(theta)*np.cos(phi)
    y = rho*np.sin(theta)*np.sin(phi)
    z = rho*np.cos(theta)
    q_s = np.array([x,y,z])
    return q_s

In [8]:
CO = 1.123384
#CO = 1.226416
CO = 1.123163
#CO = 1.229798 #CO orca GP S1
shift = 6

In [9]:
A = np.array([0,0,0])
T_1 = -A
test_a = A + T_1
print(test_a)
B = np.array([1.31132064,1.34764614,0.19767182])
#B = np.array([1,1,1])
B_1 = B + T_1
B_cts = cts(B_1)
print(B_cts)
C_s = np.array([B_cts[0]+10-5, B_cts[1], B_cts[2]])
C_s = np.array([shift, B_cts[1], B_cts[2]])
print(C_s)
D_s = np.array([shift+CO, B_cts[1], B_cts[2]])
print(D_s)
C = stc(C_s)-T_1
D = stc(D_s)-T_1
print("carbon", C)
print("oxygen", D)

[0 0 0]
[ 1.89071047 83.99881896 45.78269815]
[ 6.         83.99881896 45.78269815]
[ 7.123163   83.99881896 45.78269815]
carbon [4.16135837 4.27663408 0.62729378]
oxygen [4.94033899 5.07719361 0.74471931]


In [10]:
print(np.sign(10))

1
